Repository cordada/drf-pagination-utils, pull requests merged in 2025-03, with the labels that each got.

#244 deps: Update `pip` from 23.1.2 to 24.2
  Makefile
Labels: dependencies

#245 deps: Update `pip-tools` from 6.14.0 to 7.4.1
  Makefile
  requirements-dev.in
  requirements-dev.txt
Labels: dependencies

#246 Replace hardcoded version of Pip Tools in Make variable
  Makefile
Labels: task

#247 Add `--allow-unsafe` to Pip Compile arguments
  make/python.mk
  requirements-dev.txt
  requirements.txt
Labels: task

#248 Replace hardcoded versions of Pip and others in Make variables
  Makefile
Labels: task

#249 Require Python ≥ 3.9
  pyproject.toml
Labels: task

#251 Deploy release v1.5.3
  .black.cfg.toml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  Makefile
  make/python.mk
  mypy.ini
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
Labels: task, kind: deploy

#252 Fix release v1.5.3
  pyproject.toml
Labels: bug, kind: release

#253 Deploy release v1.5.3
  pyproject.toml
Labels: task, kind: deploy
